feat: add menu bar item to clear data
Vencord/Vesktop pull request #53
Opened 2023-07-09 09:28 UTC by ryanccn

2023-07-09 09:38 UTC, ryanccn commented
Not sure whether to make this button also clear Vencord Desktop settings or not, could be a good idea

2023-07-11 14:13 UTC, Vendicated commented
How do you even use this entry now that we hid the menubar?

2023-07-11 15:06 UTC, ryanccn commented
Should I also add this in Vencord Desktop Settings then?

(It's available on macOS since the menu bar is always there)

2023-07-11 19:20 UTC, Vendicated commented
having it in the tray would likely be the most logical

![image](https://github.com/Vencord/Desktop/assets/45497981/bd09ca14-ff91-4304-b0ed-35565e15e7f0)

2023-07-13 17:09 UTC, Vendicated commented on src/main/mainWindow.ts
> +        defaultId: 0,
consider using a const enum for this

2023-07-13 17:09 UTC, Vendicated commented on src/main/mainWindow.ts
> +        message: "Are you sure you want to reset Vencord Desktop?",
```suggestion
        message: "Are you sure you want to reset Vencord Desktop? This will log you out and clear other local settings.",
```

2023-07-13 17:11 UTC, Vendicated requested changes
Aside my other proposed changes,
- Please update the name from Vencord Desktop to Vesktop
- "reset Vesktop" kind of implies that Vesktop settings are also reset, which is not actually the case. We should either also reset those settings or rephrase it

2023-07-14 00:11 UTC, Vendicated approved these changes

2023-07-14 00:14 UTC, merged

2023-07-14 00:15 UTC, Vendicated commented
thank you!